### ISSUE TITLE
Missing c.ImplicitCandidate

### ISSUE THREAD

**Issue by dwijnand** [milessabin/macro-compat#22]
As used by [Generic1Macros](https://github.com/milessabin/shapeless/blob/5289c969064321f1e1aa9b3dd24f134f216ed1a9/core/src/main/scala/shapeless/generic1.scala#L156-L166).

If you know what the 2.10 equivalent is I can send the pull request. Thanks.

**Comment by milessabin** [comment]
The equivalent is a tuple ... I think you can probably fake it with an extractor.

**Comment by dwijnand** [comment]
I see. But where do I find [pre: Type, sym: Symbol](https://github.com/scala/scala/blob/v2.11.7/src/reflect/scala/reflect/macros/whitebox/Context.scala#L52) given I have only a [(Type, Tree)](https://github.com/scala/scala/blob/v2.10.6/src/reflect/scala/reflect/macros/Typers.scala#L37)? :-/

**Comment by milessabin** [comment]
I think you might not actually need them to have sensible values to do the right thing, at least as used in shapeless. Beyond that you'd need to dig into the 2.11.x source and find out where the values come from.

**Comment by milessabin** [comment]
It should be doable ... most likely you'll need to cast to internals.

**Comment by dwijnand** [comment]
I think I found [some relevant code](https://github.com/milessabin/shapeless/blob/207e1a487f8addd7e08dd832d842072cfeb64093/core/src/main/scala/shapeless/orphans.scala#L59-L69) in the scala-2.10.x branch of shapeless for how this should be implemented.

**Comment by milessabin** [comment]
Oh! Yes! Bingo!

I'd completely forgotten about that :-)

**Comment by dwijnand** [comment]
Fixed with https://github.com/milessabin/macro-compat/commit/af16d5eb6f64f7312b3398daebf8d259fa060272
