### ISSUE TITLE
Crash with whitebox bundle extending blackbox bundle

### ISSUE THREAD

**Issue by japgolly** [milessabin/macro-compat#25]
Hello. I recently submitted a patch to Monocle and ran into an issue where a whitebox macro bundle, extending a blackbox macro bundle, works fine in Scala 2.11 but causes Scala 2.10 to crash.

You can view the scalac barf here:
https://travis-ci.org/julien-truffaut/Monocle/jobs/92380184

And the macro bundles here:
https://github.com/japgolly/Monocle/blob/04e64d5a55358a1b40093a3451cbfe48770c0431/macro/src/main/scala/monocle/macros/GenIso.scala

**Comment by milessabin** [comment]
My gut feeling is that it's the `override val` which is the problem rather than the boxity.

Could you try making the context whitebox and abstract in `GenIsoImpl` and have just a concrete whitebox val in `GenIsoImplW`.

**Comment by japgolly** [comment]
> Could you try making the context whitebox and abstract in GenIsoImpl and have just a concrete whitebox val in GenIsoImplW.

Do you mean that as an experiment to see what will happen, or as a solution suggestion? If the latter, then we'd just have two sets of whitebox macros in which case there'd be no need to have them in different classes, where as my wish was to keep as many macros as possible black, and make the necessary ones white whilst still being able to share code.

By the way, I forgot to mention that I worked around this by removing the direct relationship between the two bundles, and introducing a `@bundle abstract class A` from which they both now derive.

**Comment by milessabin** [comment]
As an experiment primarily. But, now you mention it, yes, you really might as well use whitebox throughout.

**Comment by milessabin** [comment]
WRT your workaround, that does suggest it's the `override val` which is the issue.

**Comment by japgolly** [comment]
Nice :+1:
