### ISSUE TITLE
Consider if type is existential when calling dealias?

### ISSUE THREAD

**Issue by dwijnand** [milessabin/macro-compat#31]
Currently `Type#dealias` is defined as an alias for `normalize`: [[1](https://github.com/milessabin/macro-compat/blob/v1.1.0/core/src/main/scala_2.10/macrocompat/macrocompat.scala#L114)]

But according to Shapeless for Scala 2.10, it should consider if the type is existential: [[2](https://github.com/milessabin/shapeless/blob/2e4a784c27cf2d6ed46dc01818adc4497110500e/core/src/main/scala/shapeless/typeable.scala#L351-L354)]

Should the definition here of `dealias` take that into account?

**Comment by milessabin** [comment]
Good spot. Yes, semantics of `dealias` in 2.11.x aren't quite the same as `normalize` in 2.10.x. I'll ask on scala/contributors ...

**Comment by dwijnand** [comment]
In that case, perhaps the special casing of `typeArgs` is in the same boat: https://github.com/milessabin/shapeless/blob/2e4a784c27cf2d6ed46dc01818adc4497110500e/core/src/main/scala/shapeless/typeable.scala#L361-L362

**Comment by milessabin** [comment]
Yes, that's related IIRC.

**Comment by milessabin** [comment]
See discussion [here](https://gitter.im/scala/contributors?at=5652f7fa54ba2ca2426134b7). @retronym is suggesting,

``` scala
def dealias(t: Type) = t match {
  case _ if t.takesTypeArgs => t
  case _ : RefinedType => t
  case _ => t.normalize
}
```

We could also try with and without a special case for `ExistentialType`.

**Comment by dwijnand** [comment]
More evidence that `dealias` (and `typeArgs`) needs tweaking with regards to `ExistentialType`:

```
    // Doesn't work, bug in macro-compat
//  val dealiased = tpe.dealias
    val dealiased = tpe match {
      case existential: ExistentialType => existential
      case other => other.normalize
    }
```

```
    dealiased match {
...
      case ExistentialType(quantified, underlying) =>
        // Doesn't work, bug in macro-compat
    //  val tArgs = dealiased.typeArgs
        val TypeRef(_, _, tArgs0) = underlying
        val tArgs = tArgs0.map { tpe => if(tpe.typeSymbol.asType.isExistential) typeOf[Any] else tpe }
...
```

**Comment by dwijnand** [comment]
For more context, those are taken from trying to migrate the Scala 2.10 variant of Shapeless' `TypeableMacros`, and the failure is that the test code in `core/src/test/scala/shapeless/typeable.scala` doesn't compile (if I recall correctly the error was "can't find Typeable instance for this type")

**Comment by dwijnand** [comment]
```
[error] /Users/dnw/dev/shapeless-2.10/core/src/test/scala/shapeless/typeable.scala:367: could not find implicit value for parameter castU: shapeless.Typeable[Either[Int, _]]
[error]     val cei3 = ei.cast[Either[Int, _]]
[error]                       ^
[error] /Users/dnw/dev/shapeless-2.10/core/src/test/scala/shapeless/typeable.scala:380: could not find implicit value for parameter castU: shapeless.Typeable[Either[_, String]]
[error]     val ces3 = es.cast[Either[_, String]]
[error]                       ^
[error] two errors found
```

**Comment by dwijnand** [comment]
I tried a bunch of different combinations, both in here and in combination with different .typeArgs implementation.

I have no idea, I've just special-cased the two instances I found:

https://github.com/milessabin/shapeless/blob/495e275c144e907cc636dc612bc293c80af3ecce/core/src/main/scala_2.10/shapeless/compat.scala#L81-L96

I don't see a point in continuing to keep this issue open.

**Comment by milessabin** [comment]
I'm going to reopen this because I'd like to take another look. Can you say what you tried as implementations of `dealias` and `typeArgs`? Did you go as far as copy/pasting the 2.11.x definitions into macro-compat?

**Comment by dwijnand** [comment]
:+1:

I tried different combinations (merges) of possible definitions of `Type#dealias` between

``` scala
val dealiased = tpe match {
  case existential: ExistentialType => existential
  case other => other.normalize
}
```

and

``` scala
def dealias(t: Type) = t match {
  case _ if t.takesTypeArgs => t
  case _ : RefinedType => t
  case _ => t.normalize
}
```

that @retronym recommended, in combinations with possible definitions of `Type#typeArgs` between

``` scala
def typeArgs: List[Type] = tpe match {
  case TypeRef(_, _, args) => args
  case _ => Nil
}
```

and

``` scala
def typeArgs: List[Type] = tpe match {
  case TypeRef(_, _, args) => args.map { tpe => if(tpe.typeSymbol.asType.isExistential) typeOf[Any] else tpe }
  case _ => Nil
}
```

and something somewhere (sorry it was a little while ago) broke in shapeless' build.

**Comment by milessabin** [comment]
Thanks ... I'll try the copy/paste from 2.11.x approach :-)

**Comment by milessabin** [comment]
Fixed in 5bbf257a8747b3c2c0cd27f7f845b79f899c359b.

**Comment by dwijnand** [comment]
Very cool, thank you.

**Comment by milessabin** [comment]
Possibly a bit hasty. Back in shapeless `dealias` is looking good, but `typeArgs` isn't quite the same.

**Comment by dwijnand** [comment]
oh

**Comment by milessabin** [comment]
Done :-)
