### ISSUE TITLE
Publish for Scala 2.12.0-RC1

### ISSUE THREAD

**Issue by alexandru** [milessabin/macro-compat#67]
Please publish for 2.12.0 RC1 :-)

**Comment by milessabin** [comment]
I'm waiting on macro-paradise.

**Comment by dwijnand** [comment]
Release v1.1.1 was released for Scala 2.12.0-RC1:
- http://search.maven.org/#artifactdetails%7Corg.typelevel%7Cmacro-compat_2.12.0-RC1%7C1.1.1%7Cjar
- http://search.maven.org/#artifactdetails%7Corg.typelevel%7Cmacro-compat_sjs0.6_2.12.0-RC1%7C1.1.1%7Cjar

**Comment by ghost** [comment]
:+1:
