### ISSUE TITLE
abstract type pattern is unchecked since it is eliminated by erasure

### ISSUE THREAD

**Issue by julien-truffaut** [milessabin/macro-compat#71]
I got the following error in scala 2.10 once I upgraded from 1.1.0 to 1.1.1

https://travis-ci.org/julien-truffaut/Monocle/jobs/169164862

**Comment by milessabin** [comment]
Can you point me at the corresponding source?

**Comment by julien-truffaut** [comment]
sure:
https://github.com/julien-truffaut/Monocle/blob/master/macro/shared/src/main/scala/monocle/macros/GenIso.scala#L116-L117
https://github.com/julien-truffaut/Monocle/blob/master/macro/shared/src/main/scala/monocle/macros/Lenses.scala#L58
https://github.com/julien-truffaut/Monocle/blob/master/macro/shared/src/main/scala/monocle/macros/Lenses.scala#L69
https://github.com/julien-truffaut/Monocle/blob/master/macro/shared/src/main/scala/monocle/macros/Lenses.scala#L80

**Comment by julien-truffaut** [comment]
Thanks @milessabin, you're fixed worked :)

**Comment by milessabin** [comment]
For the record the fix (I think it is a fix rather than a workaround) is to use patterns of the form,

``` scala
case n: TermName => ...
case n: TypeName => ...
```

rather than,

``` scala
case n@TermName(_) => ...
case n@TypeName(_) => ...
```

**Comment by dwijnand** [comment]
@milessabin Can you explain why the latter doesn't work in 2.10?

**Comment by milessabin** [comment]
It seems that the extractors are being viewed as non-stable.

**Comment by dwijnand** [comment]
Personally I would qualify that as an issue with macro-compat that requires a workaround in user-land.

I wonder what project required support for them in macro-compat in the first place: https://github.com/milessabin/macro-compat/commit/83ceac1c34b0ec9e4eeb7cc45fd41648555d1aee
