### ISSUE TITLE
Release for 2.13.0

### ISSUE THREAD

**Issue by eed3si9n** [milessabin/macro-compat#86]
macro-compat shows up as a dependency of Minitest, which I'm using for scopt.
I'd appreciate if 2.13 artifact is available for macro-compat.

**Comment by milessabin** [comment]
See the discussion on #85 from here: https://github.com/milessabin/macro-compat/pull/85#issuecomment-500201690.

Does the local definition strategy for 2.13.0 work for you and/or Minitest?
